name: Build
on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths:
      - submissions/minimal/**
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
    paths:
      - submissions/minimal/**
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
          
    - name: Build service
      run: unset JAVA_HOME; nix run .#submissions.minimal
