name: Build
on:
  push:
    branches: 
      - master
    paths:
      - submissions/minimal
    paths-ignore:
      - README.md
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
    paths:
      - submissions/minimal
    paths-ignore:
      - README.md
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
          
    - name: Build service
      run: nix build .#submissions.minimal
